---
# debug-pod.yaml
# Temporary pod for debugging and accessing the PersistentVolume
# Note: Update the namespace to match your deployment (default is 'default')
apiVersion: v1
kind: Pod
metadata:
  name: routeros-debug
  # Update this namespace to match your deployment
  # For example: namespace: routeros-checker
  namespace: default
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: routeros-version-data
  restartPolicy: Never
