---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: routeros-version-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Optionally specify a storage class
  # storageClassName: standard
