name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarqube:
    uses: CalebSargeant/reusable-workflows/.github/workflows/sonarqube.yaml@main
    with:
      sonar_project_key: "CalebSargeant_mikrotik-chr"
      sonar_organization: "calebsargeant"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}